apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iot-monitoring
resources:
  - namespace.yaml
  - configmaps.yaml
  - secret.yaml
  - storage.yaml
  - postgres.yaml
  - kafka.yaml
  - ingestion.yaml
  - storage-consumer.yaml
  - dashboard.yaml
  - load-test-dashboard-rbac.yaml
  - load-test-dashboard.yaml
