apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: iot-monitoring
type: Opaque
stringData:
  POSTGRES_USER: iot
  POSTGRES_PASSWORD: iot
  POSTGRES_DB: iot_monitoring
  POSTGRES_DSN: postgresql://iot:iot@postgres:5432/iot_monitoring
