apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: iot-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: iot-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: load-test-results
  namespace: iot-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
